spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ctd:
  upload:
    path: C:/file/upload/
  download:
    path: C:/file/download/
logging:
  level:
    com.snf.dsds: debug
