spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/ctd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
ctd:
  upload:
    path: /var/ctdServerFile/upload/
  download:
    path: /var/ctdServerFile/download/
  isprod: true
logging:
  level:
    com.snf.dsds: info
