spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456789
    url: jdbc:mysql://192.168.1.103:3306/ctd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      # 初始连接数
      initialSize: 20
      # 最小连接池数量
      minIdle: 30
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ctd:
  upload:
    path: C:/file/upload/
  download:
    path: C:/file/download/
logging:
  level:
    com.snf.dsds: debug
server:
  port: 8081
