package com.snf.dsds.common.projectEnum;

public enum ParsExcelEnum {
    VOYAGE_NUMBER,
    SHIP_NAME,
    PLATFORM_TYPE,
    PLATFORM_NAME,
    STATION_NUM,
    START_TIME,
    FINISH_TIME,
    DIVE_NUM,
    LONGITUDE_LAYOUT,
    LATITUDE_LAYOUT,
    DEPTH_LAYOUT,
    LONGITUDE_WORK,
    LATITUDE_WORK,
    DEPTH_WORK,
    DEV_TYPE,
    DEV_MODEL,
    DEV_SN,
    DATA_SET_SN,
    DATA_FORMAT,
    DATA_STATUS,
    DATA_FILE_NAME,

}
