spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: chen123456
#    url: jdbc:mysql://127.0.0.1:3306/ctd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: 123456789
#    url: jdbc:mysql://192.168.1.102:3306/ctd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  profiles:
    active: prod
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.snf.dsds.dao

